// <auto-generated />
using System;
using AzubiManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzubiManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518120139_AddPasswortGeandert")]
    partial class AddPasswortGeandert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzubiManager.Api.Models.Aufgabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AusbilderId")
                        .HasColumnType("int");

                    b.Property<int?>("AzubiId")
                        .HasColumnType("int");

                    b.Property<string>("AzubiIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Erledigt")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Faelligkeitsdatum")
                        .HasColumnType("date");

                    b.Property<bool>("IstGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Prioritaet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AusbilderId")
                        .HasDatabaseName("IX_Aufgaben_AusbilderId");

                    b.HasIndex("AzubiId");

                    b.HasIndex("AusbilderId", "Erledigt")
                        .HasDatabaseName("IX_Aufgaben_Ausbilder_Erledigt");

                    b.ToTable("Aufgaben");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nachname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PasswortGeandert")
                        .HasColumnType("bit");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vorname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Notiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AusbilderId")
                        .HasColumnType("int");

                    b.Property<int?>("AzubiId")
                        .HasColumnType("int");

                    b.Property<string>("AzubiIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inhalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AusbilderId")
                        .HasDatabaseName("IX_Notizen_AusbilderId");

                    b.HasIndex("AzubiId");

                    b.ToTable("Notizen");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Tagesstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AzubiId")
                        .HasColumnType("int");

                    b.Property<string>("Bemerkung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AzubiId", "Datum")
                        .HasDatabaseName("IX_Tagesstatus_Azubi_Datum");

                    b.ToTable("TagesstatusListe");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Teilnehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abteilung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AusbilderId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ausbildungsende")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Ausbildungsstart")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Geburtsdatum")
                        .HasColumnType("date");

                    b.Property<string>("Gruppe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kurs")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Lehrjahr")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AusbilderId")
                        .HasDatabaseName("IX_Teilnehmer_AusbilderId");

                    b.ToTable("Teilnehmer");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AusbilderId")
                        .HasColumnType("int");

                    b.Property<int?>("AzubiId")
                        .HasColumnType("int");

                    b.Property<string>("AzubiIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Endzeit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AusbilderId")
                        .HasDatabaseName("IX_Termine_AusbilderId");

                    b.HasIndex("AzubiId");

                    b.HasIndex("AusbilderId", "Datum")
                        .HasDatabaseName("IX_Termine_Ausbilder_Datum");

                    b.ToTable("Termine");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Aufgabe", b =>
                {
                    b.HasOne("AzubiManager.Api.Models.Benutzer", "Ausbilder")
                        .WithMany()
                        .HasForeignKey("AusbilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzubiManager.Api.Models.Teilnehmer", "Azubi")
                        .WithMany("Aufgaben")
                        .HasForeignKey("AzubiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ausbilder");

                    b.Navigation("Azubi");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Notiz", b =>
                {
                    b.HasOne("AzubiManager.Api.Models.Benutzer", "Ausbilder")
                        .WithMany()
                        .HasForeignKey("AusbilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzubiManager.Api.Models.Teilnehmer", "Azubi")
                        .WithMany("Notizen")
                        .HasForeignKey("AzubiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ausbilder");

                    b.Navigation("Azubi");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Tagesstatus", b =>
                {
                    b.HasOne("AzubiManager.Api.Models.Teilnehmer", "Azubi")
                        .WithMany("TagesstatusListe")
                        .HasForeignKey("AzubiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azubi");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Teilnehmer", b =>
                {
                    b.HasOne("AzubiManager.Api.Models.Benutzer", "Ausbilder")
                        .WithMany("Teilnehmer")
                        .HasForeignKey("AusbilderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ausbilder");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Termin", b =>
                {
                    b.HasOne("AzubiManager.Api.Models.Benutzer", "Ausbilder")
                        .WithMany()
                        .HasForeignKey("AusbilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzubiManager.Api.Models.Teilnehmer", "Azubi")
                        .WithMany("Termine")
                        .HasForeignKey("AzubiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ausbilder");

                    b.Navigation("Azubi");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Benutzer", b =>
                {
                    b.Navigation("Teilnehmer");
                });

            modelBuilder.Entity("AzubiManager.Api.Models.Teilnehmer", b =>
                {
                    b.Navigation("Aufgaben");

                    b.Navigation("Notizen");

                    b.Navigation("TagesstatusListe");

                    b.Navigation("Termine");
                });
#pragma warning restore 612, 618
        }
    }
}
